---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"

baseurl: "http://www.houvong.net"
title: "Zbra! Hey!"

permalinks:
    post: /:year/:month/:title/

params:
    # used in atom (RSS) feed
    author: Tien Peng HOUVONG
    GitHubUser: "tphouvong"
    tagline: "Zbra! Hey!"
    description: >
        Yet another blog about IT stuff from a junior network engineer.
    repo: "https://github.com/tphouvong"
    version: "0.0.2"
---
